// Adjectives that modify entities

export const ADJ = [
    // === Core brainrot adjectives ===
    "sus", "sigma", "based", "goated", "bussin", "mid", "delulu",
    "zesty", "unhinged", "brainrotted", "fire", "no-cap",
    "valid", "Ohio-level", "skibidi-coded", "rizz-worthy",
    "mog-worthy", "aura-maxed", "gyatt-tier", "NPC-coded",
    "Griddy-ready", "fanum-taxed", "hawk-tuah-certified",
    "looksmaxxed", "bonesmashed", "cooked", "absolutely diabolical",
    "lowkey fire", "highkey mid", "unironically goated",
    "certified classic", "big ahh", "goofy ahh", "devious",
    "locked in", "ong fr fr", "rent-free",
    "chronically online", "terminally online", "tweaking",
    "down bad", "up good", "edged", "mewed", "slay",
    "ate", "giving", "serving", "whole ahh", "on demon time",
    "yapped-out", "glazed-up", "ratio-proof", "L-resistant",
    "W-magnetized", "aura-leaking", "copium-fueled",
    "brainrot-adjacent", "NPC-adjacent",

    // === Quality / tier adjectives ===
    "peak", "elite", "cracked", "S-tier", "A-tier",
    "D-tier", "F-tier", "bottom-tier", "god-tier",
    "top-tier", "built different", "different gravy",
    "hard", "raw", "gas", "heat", "tuff",
    "clean", "crispy", "icy", "dripped out",
    "legendary", "mythical", "iconic", "canon",
    "SSS-tier", "Z-tier", "negative-tier",
    "ascended-tier", "omega-tier", "prestige-tier",
    "cracked out of their mind", "different breed",
    "ungodly", "supernatural", "transcendent",
    "otherworldly", "unfathomable", "incomprehensible",
    "diamond-tier", "netherite-tier", "void-tier",
    "final-boss-tier", "tutorial-level",
    "pay-to-win", "free-to-play-coded",

    // === Negative adjectives ===
    "cringe", "basic", "wack", "ass", "trash",
    "toxic", "bruh-tier", "down horrendous", "finished",
    "washed", "flopped", "fumbled", "booty",
    "chopped", "busted", "janky", "scuffed",
    "mid at best", "bottom-of-the-barrel", "poverty-tier",
    "cooked beyond repair", "irredeemable", "unsalvageable",
    "cursed", "blursed", "abysmal", "atrocious",
    "putrid", "ghastly", "horrendous", "egregious",
    "diabolically mid", "aggressively mid",
    "offensively basic", "criminally unfunny",
    "bone-dry", "dust-tier", "ash-tier",
    "NPC-quality", "filler-arc-coded", "stock-footage-tier",
    "early-access", "beta-build", "pre-alpha",
    "unpatched", "zero-day", "bricked",

    // === Personality / vibe adjectives ===
    "demure", "brat", "mindful", "cutesy",
    "snatched", "iconic", "camp", "extra", "chaotic",
    "feral", "unwell", "foul", "wild", "insane",
    "diabolical", "menacing", "villainous", "evil",
    "parasocial", "deranged", "chronically online",
    "deranged in the best way", "unserious", "aggressively silly",
    "violently chill", "aggressively unbothered",
    "suspiciously calm", "menacingly polite",
    "disturbingly normal", "weaponized", "militarized",
    "tactical", "strategic", "calculated",
    "chaotic neutral", "lawful evil", "true neutral",
    "chaotic good", "neutral evil",
    "unhinged but make it fashion",
    "feral but in a cute way",
    "delulu but thriving",
    "toxic but self-aware",

    // === Looksmaxxing adjectives ===
    "mogged", "fragged", "PSL-rated",
    "softmaxxed", "hardmaxxed", "frauding",
    "hunter-eyed", "positive-canthal-tilted",
    "Chad-coded", "Stacy-coded", "normie-tier",
    "subhuman-tier", "blackpilled", "redpilled", "bluepilled",
    "purplepilled", "whitepilled", "dogpilled", "honkpilled",
    "norwooded", "recessed", "forward-grown",
    "mewing-enhanced", "bonesmash-approved",
    "jawline-havin", "symmetry-blessed",
    "genetically-lottery-winning", "phenotype-mogging",
    "bone-structure-havin", "eye-area-blessed",

    // === Italian brainrot adjectives ===
    "Bombardiro-coded", "Tralalero-pilled",
    "Tung Tung Tung certified", "Patapim-approved",
    "Italian brainrot tier",
    "Cappuccino-coded", "Spaghettini-pilled",
    "full-on Crocodilo", "Bananini-maxed",
    "Tortellini-tier", "Linguini-coded",
    "Panzerini-approved", "Rigatoni-pilled",

    // === Compound intensifier adjectives ===
    "absolutely unhinged", "certifiably insane",
    "clinically brainrotted", "cosmically mid",
    "existentially cooked", "transcendently based",
    "omega-level sigma", "maximum rizz",
    "astronomically down bad", "interdimensionally sus",
    "quantumly entangled with the L",
    "metaphysically mogged", "spiritually cooked",
    "philosophically mid", "theologically sus",
    "biologically cringe", "chemically imbalanced but vibing",
    "gravitationally pulled toward the L",
    "photosynthetically based", "geologically ancient",
    "mathematically impossible", "statistically improbable",
    "legally questionable", "medically concerning",
    "academically fraudulent", "economically ruinous",
    "architecturally unsound", "structurally compromised",
    "emotionally devastating", "psychologically scarring",

    // === Internet culture adjectives ===
    "NPC-brained", "bot-coded", "algorithm-blessed",
    "FYP-worthy", "algorithm-cursed", "shadow-banned",
    "ratio-proof", "community-noted", "fact-checked",
    "AI-generated", "deepfaked", "AI-slop-tier",
    "stock-photo-coded", "LinkedIn-coded", "Quora-coded",
    "Reddit-brained", "Twitter-poisoned", "TikTok-rotted",
    "Discord-modded", "Twitch-chatted",
    "4chan-pilled", "Tumblr-coded",
    "Pinterest-aesthetic", "BeReal-caught",
    "Threads-irrelevant", "Snapchat-scored",
    "Wikipedia-cited", "Fandom-wiki-edited",
    "Steam-reviewed", "Rotten-Tomatoes-rated",
    "IMDb-scored", "Letterboxd-reviewed",

    // === Gaming adjectives ===
    "nerfed", "buffed", "OP", "meta",
    "off-meta", "griefing", "throwing", "clutch",
    "sweaty", "try-hard", "casual", "noob",
    "bot-lobby", "ranked", "unranked",
    "hardstuck", "boosted", "smurfing",
    "tilted", "on-tilt", "one-shot",
    "one-tapped", "wallhacked", "aim-botted",
    "pixel-perfect", "frame-perfect",
    "RNG-blessed", "RNG-cursed",
    "save-scummed", "permadeath-coded",

    // === Food-coded adjectives ===
    "unseasoned", "well-seasoned", "deep-fried",
    "raw (like sushi)", "half-baked", "overcooked",
    "marinated in delusion", "basted in cope",
    "room-temperature IQ", "lukewarm take-having",
    "microwave-dinner-coded", "Michelin-star",

    // === Weather / nature adjectives ===
    "drought-tier", "flood-level", "tsunami-grade",
    "earthquake-coded", "solar-flare-pilled",
    "extinction-event-tier", "ice-age-coded",
    "volcano-coded", "monsoon-brained",

    // === Sound-coded adjectives ===
    "eardrum-shattering", "whisper-quiet menace",
    "bass-boosted", "auto-tuned", "reverb-coded",
    "dial-up-speed", "earworm-infected",

    // === Architecture / structure adjectives ===
    "load-bearing", "structurally unsound",
    "condemned-building-coded", "penthouse-tier",
    "basement-dwelling", "attic-coded",
    "foundation-cracking", "earthquake-resistant",
];
