// Interjections, question openers, asides, attributions, and consequences

export const INTERJ = [
    // === Exclamations ===
    "Sheesh!", "Bruh.", "Gyatt!", "Yeet!", "Slay!",
    "Periodt.", "Bet.", "Say less.", "Facts.", "W.",
    "Ayo?", "Pause.", "Nah.", "Oof.", "Yikes.",
    "Ick.", "Ew.", "Zamn!", "Damn.", "Bro.",
    "Unc!", "Dawg.", "Fam.", "Gang.", "Twin.",
    "Chat.", "Bestie.", "Girlie.", "Queen.", "King.",
    "SKIBIIII!", "HAWK TUAH!", "SIX SEVEN!",
    "BOMBARDIRO!", "TRALALERO!",
    "Amogus.", "Sussy.", "Mogged.", "Glazed.", "Cooked.",
    "Ratioed.", "Blocked.", "Reported.", "Cancelled.",
    "MORBIUS!", "ITS MORBIN TIME!", "EMOTIONAL DAMAGE!",
    "VIOLATION!", "FATALITY!", "FINISH HIM!",
    "GG.", "EZ.", "Diff.", "Clutch!", "Choke.",
    "Whiff.", "Sadge.", "KEKW.", "OMEGALUL.",
    "Copium.", "Hopium.", "Gigachad.", "Based.",
    "Yoink.", "Jebaited.", "Gottem.", "Bozo.",

    // === Discourse openers ===
    "No cap,", "Respectfully,", "On god,", "Fr fr,",
    "Nah because", "Ong,", "Deadass,", "Hold up,",
    "Not gonna lie,", "Hear me out,", "Nah wait,",
    "Real talk,", "It's giving.", "Lowkey,", "Highkey,",
    "I'm not even gonna hold you,", "Look,",
    "Okay but like,", "Yo so basically,",
    "I'm dead,", "I'm crying,", "I'm screaming,",
    "Nah fam,", "Bro I swear,", "Ayo wait,",
    "Now hold on,", "Okay hear me out though,",
    "No because why is", "Nah who did this,",
    "This is sending me,", "I'm hollering,",
    "I can't breathe,", "Somebody come get they mans,",
    "Plot twist:", "Lore drop:", "Character development:",
    "Not me discovering that", "The way that",
    "The fact that", "POV:", "Live footage of",
    "Breaking news:", "This just in:",
    "Okay but unironically,", "I can't make this up,",
    "Real ones know,", "Sleep on this if you want,",
    "Mark my words,", "Remember this tweet,",
    "Storytime:", "So get this,",
    "Okay so boom,", "Alright check it,",
    "Yooo,", "Nahhhhh,", "STOPPP,",
    "I'm actually crying,", "I can't do this anymore,",
    "The internet was a mistake because",
    "Normalize talking about how",
    "We need to discuss the fact that",

    // === Commentary / reaction markers ===
    "W take:", "L take:", "Massive W:", "Huge L:",
    "Bro is cooked.", "Chat is this real?",
    "Nah this is crazy.", "I can't even.",
    "Bro think he the main character.", "Chat I'm dead.",
    "This is peak.", "This is mid.", "This is canon.",
    "This ain't it.", "We move.", "It's over.",
    "It's so over.", "We are so back.",
    "It's joever.", "We are so cooked.",
    "Cope.", "Seethe.", "Mald.", "Touch grass.",
    "Skill issue.", "Ratio + L + fell off.",
    "Who asked though?", "Nobody asked.",
    "Caught in 4K.", "Caught lacking.",
    "Rent free.", "Main character syndrome.",
    "The delusion is real.", "The audacity.",
    "Not the ick.", "Red flag.", "Green flag.",
    "Beige flag.", "Walking red flag.",
    "Alexa play Despacito.", "Narrator: they were cooked.",
    "Curb Your Enthusiasm theme plays.",
    "And I oop—", "The math is not mathing.",
    "The vibes are off.", "The vibes are immaculate.",
    "This is cinema.", "This is art.", "This is lore.",
    "And that's on what?", "Say it louder.",
    "The ghetto.", "The hood classic.",
    "Common W.", "Common L.", "Rare W.", "Rare L.",
    "Hall of fame W.", "Hall of shame L.",
    "W + ratio + you fell off.", "L + cope + seethe + mald.",
    "That's tuff.", "Couldn't be me.", "Stay safe out there.",
    "It's giving what it's supposed to give.",
    "This is not the serve you think it is.",
    "The call is coming from inside the house.",
    "The villain origin story writes itself.",
];

export const QWORD = [
    // === Basic question openers ===
    "Why is", "How is", "When did", "What if", "Who let",
    "Where did", "Why did", "Did", "Has",
    "Why does", "How does", "What does",

    // === Brainrot question openers ===
    "Bro why is", "Chat why is", "Nah why is", "Ayo how is",
    "Fr why did", "Since when did", "Bro who let",
    "Chat is", "Dawg why is", "Fam how is",
    "Nah who let", "Ayo who let", "Wait why is",
    "Hold up why is", "Bruh how did", "Nah fr why did",
    "What the sigma is", "What in the Ohio is",
    "What in the Skibidi Toilet is", "Why on god is",
    "Bro what in the actual brainrot is",
    "Chat can someone explain why", "Nah because why is",
    "Not gonna lie why is", "Since when could",
    "How in the Bombardiro Crocodilo did",
    "Why in the Italian brainrot did",
    "Chat am I tweaking or did",
    "Is it just me or did", "Does anyone else think",
    "Can we talk about how", "Why is no one talking about how",

    // === Expanded question openers ===
    "Who in their right mind let",
    "What in the multiverse is",
    "How on this cursed earth did",
    "When in the timeline did",
    "Why in the sigma playbook did",
    "Chat be honest is", "Nah but fr fr why is",
    "Somebody please explain why",
    "In what universe did",
    "At what point did", "How many aura points did it cost when",
    "Whose villain arc included", "What in the anime is",
    "How in the actual NPC behavior did",
    "Chat I need to know why", "Why is the algorithm showing me",
    "Who gave permission for", "What happened to",
    "Am I the only one who noticed",
    "Is the simulation broken because", "Did the devs patch",
    "Who wrote the lore where", "What DLC included",
    "Which timeline are we in where",
    "How many L's does it take before",
    "What is the aura cost of",
    "Who authorized", "What in the copypasta is",
    "Where in the canon did", "Why in the director's cut did",
    "How in the extended lore did",
    "What in the community notes is",
    "Bro at what frame rate did",
    "In what patch did",
];

export const ASIDE = [
    // === Classic YouTube clickbait ===
    "(not clickbait)", "(real)", "(gone wrong)",
    "(emotional)", "(3am challenge)", "(CAUGHT ON CAMERA)",
    "(cops called)", "(she cried)", "(he left)",
    "(must watch)", "(you won't believe this)",
    "(I'm shaking)", "(this is not a drill)",
    "(ASMR)", "(storytime)", "(part 47)",
    "(the sequel)", "(director's cut)",
    "(Subway Surfers gameplay below)",
    "(family guy funny moments)", "(watch till the end)",
    "(NPC behavior)", "(caught in 4k)", "(no cap)",
    "(still mogging)", "(he's actually cooked)",

    // === Escalation parentheticals ===
    "(gone sexual)", "(in the hood)", "(almost died)",
    "(he got jumped)", "(she snapped)", "(I almost got caught)",
    "(vomit warning)", "(blood warning)", "(cringe warning)",
    "(jumpscare warning)", "(18+ only)", "(viewer discretion advised)",
    "(banned from TikTok)", "(deleted scene)",
    "(the internet needs to see this)",
    "(immediately deleted but screenshotted)",
    "(mods are asleep)", "(before it gets taken down)",
    "(evidence has been submitted)",
    "(the footage has been recovered)",

    // === Commentary parentheticals ===
    "(I'm so cooked for this)", "(help me)",
    "(why is this real)", "(this can't be real)",
    "(I need therapy)", "(someone call the police)",
    "(moms would not approve)", "(dad left after this)",
    "(the simulation is broken)", "(NPC behavior detected)",
    "(aura: DESTROYED)", "(aura: +1000000)",
    "(rizz level: MAXIMUM)", "(sigma status: ACHIEVED)",
    "(mewing streak: BROKEN)", "(Ohio moment)",
    "(certified brainrot)", "(peak internet)",
    "(we've peaked as a society)", "(there's no coming back from this)",
    "(this is why aliens won't visit us)",
    "(the CIA is watching this)",
    "(my therapist is going to hear about this)",
    "(adding this to the evidence folder)",
    "(screenshotting for the group chat)",
    "(this will be on the exam)", "(citation needed)",
    "(peer reviewed)", "(FDA not approved)",
    "(terms and conditions may apply)",
    "(batteries not included)", "(results may vary)",
    "(your mileage may vary)", "(side effects include brainrot)",
    "(consult your local sigma before attempting)",
    "(void where prohibited)", "(not financial advice)",
    "(not legal advice)", "(not medical advice either)",
    "(the council will decide your fate)",
    "(the group chat has been notified)",
    "(the algorithm took note)",
    "(your aura score has been updated)",
    "(this has been flagged for review)",
    "(HR has entered the chat)",
    "(the mods have been alerted)",

    // === Meta / format parentheticals ===
    "(part 1 of 739)", "(finale)", "(lore drop)",
    "(canon)", "(not canon)", "(filler arc)",
    "(post-credit scene)", "(anime arc)",
    "(chapter 47: the reckoning)", "(season 3 episode 12)",
    "(DLC content)", "(patch notes)",
    "(Italian brainrot version)", "(Skibidi remix)",
    "(extended cut)", "(unrated version)", "(blooper reel)",
    "(director's commentary)", "(behind the scenes)",
    "(the prequel nobody asked for)", "(spin-off episode)",
    "(mid-season finale)", "(bottle episode)",
    "(recap episode)", "(the musical episode)",
    "(the crossover event)", "(the multiverse saga)",
    "(remastered in 4K brainrot)", "(fan translation)",
    "(day one patch)", "(hotfix incoming)",
    "(early access build)", "(open beta)",
    "(closed alpha)", "(release candidate)",
    "(the speedrun starts here)", "(any% category)",
    "(100% completion)", "(true ending)",
    "(bad ending)", "(secret ending)",
    "(new game plus)", "(hard mode enabled)",
];

export const ATTRIB = [
    // === Source-based attributions ===
    "According to my FYP,", "Based on the group chat lore,",
    "As the prophecy foretold,", "Sources (trust me bro) confirm",
    "Multiple TikTok analysts agree that",
    "The sigma grindset handbook states that",
    "A recent aura audit revealed that",
    "After extensive looksmax research,",
    "Per the Discord server constitution,",
    "As documented in the Backrooms wiki,",
    "The urban dictionary definition confirms",
    "According to the brainrot archives,",
    "Expert yapping analysis shows that",
    "Per the latest ratio analytics,",
    "The mewing research institute published that",
    "A longitudinal study on brain rot found that",
    "Cross-referencing multiple group chats confirms",
    "The peer-reviewed Journal of Brainrot states that",
    "A meta-analysis of TikTok comments shows that",
    "The Google Scholar of Sigma determined that",

    // === Authority-based attributions ===
    "The Council of Sigma has determined that",
    "Per the International Rizz Committee,",
    "The Aura Police have confirmed that",
    "According to the Mog Bureau of Investigation,",
    "The Ohio Department of Brainrot reports that",
    "Leading gyatt scientists have concluded that",
    "The National Institute of Yapping states that",
    "Per the Skibidi Toilet Geneva Convention,",
    "The Fanum Tax Authority has declared that",
    "According to classified Backrooms intel,",
    "The Italian Brainrot Research Institute confirms that",
    "The Bombardiro Crocodilo Task Force reports that",
    "The Federal Bureau of Aura Investigation found that",
    "The World Health Organization of Brainrot warns that",
    "The United Nations of Sigma declared that",
    "The Supreme Court of Ratio ruled that",
    "The Department of Homeland Cringe determined that",
    "The Nobel Committee for Yapping awarded",
    "NASA's Brainrot Division detected that",
    "The Pentagon's classified meme report shows",
    "The Interpol Meme Crimes Unit confirmed that",
    "The Geneva Convention on Ratio Warfare states that",
    "The Federal Aura Reserve announced that",
    "The Congressional Budget Office of Ls reports that",
    "The Centers for Brainrot Control warns that",
    "FEMA's Ratio Disaster Response Team confirms that",
    "The National Weather Service of Vibes forecasts that",
    "The Environmental Protection Agency of Aura found that",

    // === Casual / meme attributions ===
    "My source is I made it up but",
    "Trust me bro,", "Chat I'm not lying,",
    "My FBI agent just texted me and said",
    "A little bird (actually a Tralalero Tralala) told me that",
    "The algorithm has spoken and it says",
    "Every single one of my brain cells agrees that",
    "The group chat has come to a unanimous decision that",
    "After consulting with exactly zero experts,",
    "I don't have proof but I don't have doubts either that",
    "The vibes suggest that", "My Roman Empire is the fact that",
    "Not to be a yapper but", "Not to be that person but",
    "Okay so storytime:", "So get this:",
    "You're not gonna believe this but",
    "My parasocial bestie told me that",
    "I saw it in a dream and it was that",
    "The AI chatbot hallucinated that",
    "My sleep paralysis demon informed me that",
    "The intrusive thoughts are saying",
    "The fortune cookie read:", "My horoscope literally said",
    "According to a very credible Reddit comment,",
    "A random person on Omegle once said",
    "The bathroom wall at Denny's reads:",
    "My Uber driver who definitely wasn't an NPC said",
    "The shower thoughts subreddit predicted that",
    "My notes app at 3am documented that",
    "The autocorrect suggested that",
    "The Spotify Wrapped data shows that",
    "The screen time report implies that",
    "An anonymous tip to the group chat revealed that",
    "The Discord bot generated a prophecy that",
    "The Magic 8 Ball (sigma edition) says",
    "A carrier pigeon (wearing a low taper fade) delivered the message that",
];

export const CONSEQ = [
    // === Classic conclusions ===
    "and that's on period", "and everyone clapped",
    "which is lowkey iconic", "which explains the negative aura",
    "and the vibes were immaculate", "but the aura was non-recoverable",
    "causing a massive L", "resulting in a certified W",
    "leading to an aura explosion", "and nobody was surprised",
    "and chat went crazy", "which is giving main character energy",
    "and the group chat has not recovered since",
    "and honestly same", "and that's just facts",
    "which is why we can't have nice things",
    "and the timeline erupted", "but the FYP remained unbothered",
    "and it was lowkey the most sigma thing ever witnessed",

    // === Aura consequences ===
    "and the aura shift was seismic",
    "causing an aura deficit of -999999",
    "and the aura points were redistributed",
    "but the aura was already in the negatives",
    "resulting in permanent aura damage",
    "and the aura farm was destroyed",
    "leading to an aura bankruptcy filing",
    "and the aura hyperinflation began",
    "causing an aura market crash",
    "and the aura insurance refused to pay out",
    "leading to an aura class action lawsuit",
    "and the Federal Aura Reserve intervened",
    "causing aura stagflation across the timeline",
    "and the aura bubble finally burst",

    // === Dramatic conclusions ===
    "and that's how the Ohio incident started",
    "and the simulation crashed", "and the NPC broke character",
    "and the brainrot became self-aware",
    "and the backrooms expanded another level",
    "causing a rift in the sigma timeline",
    "and the Skibidi Toilet dimension collapsed",
    "and the Italian brainrot multiverse fractured",
    "and Bombardiro Crocodilo was summoned",
    "and Tung Tung Tung Sahur appeared",
    "and the Tralalero Tralala started running",
    "and the fabric of reality tore slightly",
    "and a new timeline branched off",
    "and the matrix glitched for a frame",
    "and the fourth wall shattered",
    "and the narrator gave up",
    "and the credits started rolling but nobody moved",
    "and the post-credits scene was even worse",
    "and the devs pushed an emergency hotfix",
    "and the server crashed", "and the save file corrupted",
    "and the speedrun was invalidated",
    "and the game soft-locked",

    // === Social media consequences ===
    "and the ratio was instantaneous",
    "and the post went viral for all the wrong reasons",
    "and the quote tweets were merciless",
    "and the comments section became a warzone",
    "and the screenshots were already in every group chat",
    "and the TikTok duets were unhinged",
    "and Twitter had a field day",
    "and Reddit wrote a thesis about it",
    "and the Discord server imploded",
    "and the community note wrote itself",
    "and the apology video was already in production",
    "and the PR team started drafting a statement",
    "and the Wikipedia edit war began",
    "and the subreddit was quarantined",
    "and the Discord mods went to sleep",
    "and the group chat name was changed to commemorate it",
    "and the notification sound hasn't stopped since",
    "and the trending page will never be the same",
    "and the algorithm took notes",
    "and the screen recording went viral",
    "and the voice note was leaked",
    "and the DMs were published",

    // === Existential / comedic conclusions ===
    "and at this point I don't even know anymore",
    "and honestly we deserve this",
    "and that's why the aliens haven't contacted us",
    "and the founding fathers are rolling in their graves",
    "and the simulation devs are considering a patch",
    "and nothing has been the same since",
    "and the copium reserves are depleted",
    "and there's no recovery from this",
    "and honestly? valid", "and honestly? mid",
    "and that's the last straw for this timeline",
    "and we are so cooked as a species",
    "and we are so back", "and it's so over",
    "and the W was massive", "and the L was historic",
    "but in the end it was kinda peak ngl",
    "and the therapy bills keep stacking",
    "and the Roman Empire got a little bigger",
    "and somewhere a sigma shed a single tear",
    "and the main character arc was complete",
    "and the character development was immense",
    "and the foreshadowing all made sense",
    "and the sequel was immediately greenlit",
    "and the fanfiction wrote itself",
    "and the memes will outlive us all",
    "and the internet never forgot",
    "and the screenshot will be evidence in court",
    "and that's going in the wedding speech",
    "and the obituary will mention this",
    "and the history books will record this",
    "and the documentary is already in pre-production",
    "and the Netflix adaptation was announced",
    "and the anime opening started playing",
    "and the manga went on hiatus because of it",
    "and the live-action remake somehow made it worse",
    "and the Broadway musical is in development",
    "and civilization peaked right there",
    "and entropy accelerated slightly",
    "and the heat death of the universe moved up a week",
];
