// Noun Phrases — subjects and objects in brainrot sentences

export const ENTITY = [
    // === Skibidi Toilet universe ===
    "Skibidi Toilet", "Titan Cameraman", "Titan Speakerman",
    "Titan TV Man", "the Skibidi Scientist", "G-Toilet",
    "the Cameraman", "the Speakerman", "the TV Man",
    "the Skibidi Toilet army", "the upgraded Skibidi Toilet",
    "the infected Cameraman", "the Astro Toilet",
    "the Plunger Cameraman", "the Dark Speakerman",
    "the G-Man Toilet", "the Scientist Cameraman",
    "the Giant Skibidi Toilet", "the Spider Cameraman",
    "the Clock Man", "the Multiverse Toilet",
    "the Laser Cameraman", "the Rocket Speakerman",
    "the Drill Toilet", "the Parasite Skibidi",
    "the Upgraded Titan Cameraman", "the Glitch Toilet",
    "the Alliance Cameraman", "the Secret Agent Toilet",

    // === Italian brainrot characters ===
    "Tralalero Tralala", "Bombardiro Crocodilo", "Tung Tung Tung Sahur",
    "Lirili Larila", "Brr Brr Patapim", "Ballerina Cappuccina",
    "Trippi Troppi", "Chimpanzini Bananini", "Bommodini Gusini",
    "Cappuccino Assassino", "Boneca Ambalabu", "Frigo Camelo",
    "La Vaca Saturno Saturnita", "Bobrito Bandito",
    "Cocofanto Elefanto", "Shrimpina Gattina", "Espressona Signora",
    "Orangutini Ananasini", "Blueberrini Octopussini",
    "Glorbo Fruttodrillo", "Rhino Toasterino", "Tric Trac Baraboom",
    "Brri Brri Bicus Dicus Bombicus", "Frulli Frulla",
    "Giraffoni Macaroni", "Scorpionino Drillino",
    "Pizzarello Mozzarello", "Spaghettino Serpentino",
    "Panzerini Tigerini", "Flamingini Puddinini",
    "Salamini Tortellini", "Dragorino Volcanino",
    "Pengwini Linguini", "Lobsterino Cappuccino",
    "Hamsterini Panzerini", "Croccodrilini Martini",
    "Dolphini Rigatoni", "Mosquitini Bikini",
    "Gorillini Zucchini", "Tarantulini Fettuccine",

    // === Streamers / TikTok personalities ===
    "Kai Cenat", "IShowSpeed", "Duke Dennis", "Fanum",
    "Adin Ross", "Jynxzi", "CaseOh", "MrBeast",
    "Baby Gronk", "Livvy Dunne", "Ice Spice", "Nettspend",
    "the Costco guys", "Hawk Tuah girl", "N&A Productions",
    "JellyBean", "KSI", "xQc", "Pokimane",
    "Hailey Welch", "Pinkydoll the NPC queen",
    "Sketch", "Agent 00", "Fanum Tax Fanum",
    "Ishowmeat", "Plaqueboymax", "Sturdyyyy",
    "LilyPichu", "HasanAbi", "Asmongold",
    "Tyler1", "Ninja", "DrDisrespect",
    "Sneako", "JiDion", "YourRAGE", "BruceDropEmOff",
    "Clix", "Stable Ronaldo", "TommyInnit", "Dream",
    "Quackity", "Technoblade's legacy", "SSSniperWolf",
    "Addison Rae", "Charli D'Amelio", "Khaby Lame",
    "Bella Poarch", "ZHC", "Mark Rober", "Ryan Trahan",
    "Danny Gonzalez", "Drew Gooden", "Kurtis Conner",
    "penguinz0", "Ludwig", "Ironmouse", "CDawgVA",
    "Gigguk", "ConnorEatsPants", "Jerma985",

    // === Fictional / meme characters ===
    "Quandale Dingle", "the Rizzler", "GigaChad",
    "Freddy Fazbear", "the Grimace Shake", "the Smurf Cat",
    "the Ohio final boss", "the NPC", "the Rizz God",
    "the shadow wizard money gang", "the pizza tower guy",
    "the amogus crewmate", "the sussy imposter",
    "the Backrooms entity", "King Von ghost",
    "Huggy Wuggy", "Poppy Playtime", "the Mondstadt incident",
    "the sussy baka", "the siren head", "the sus jerma face",
    "the smurf cat mushroom", "the spaghetti monster",
    "Skibidi DOP DOP Yes Yes", "the sussy among us character",
    "an NPC villager", "the sussy red crewmate",
    "Thanos but sigma", "Shrek but goated",
    "the Backrooms Partygoer", "Entity 303",
    "Herobrine", "the Lean Monster", "Morbius",
    "Saul Goodman", "Walter White's alter ego",
    "Mike Ehrmantraut", "Gus Fring's stare",
    "Patrick Bateman", "the American Psycho narrator",
    "Ryan Gosling (literally me)", "the Joker (society)",
    "Homelander milk scene", "Omni-Man",
    "Gojo Satoru", "Toji Fushiguro", "Sukuna",
    "Makima", "Power", "Eren Yeager freedom arc",
    "Levi Ackerman", "Saitama", "Goku (solo's your verse)",
    "Vegeta pride moment", "Naruto talk no jutsu",
    "Luffy Gear 5", "Zoro but lost", "Shanks' haki flex",
    "the Duolingo owl", "the Scrunkly",
    "the Blorbo from your shows", "the Meow Meow",
    "Shaggy at 0.001% power", "El Primo",
    "the Oompa Loompa jury", "the Lorax but unhinged",
    "the Onceler fandom", "the Minion uprising",
    "Megamind", "Metro Man", "Megamind but sigma",
    "the Monsters Inc door meme", "the confused math lady",

    // === Archetype characters ===
    "the sigma male", "the alpha wolf", "the beta orbiter",
    "a level 100 mewer", "the aura farmer", "the goated one",
    "the main character", "a certified yapper", "an iPad kid",
    "a chronically online person", "the mog master",
    "a brain-rotted zoomer", "the Sigma grindset enjoyer",
    "the aura check survivor", "a mewing streak holder",
    "a no-fap warrior", "the edge lord", "the looksmax consultant",
    "a whole ahh moment", "a devious licker",
    "the discord kitten", "a parasocial Andy", "the gyatt inspector",
    "your FBI agent", "the Subway Surfers narrator",
    "a Family Guy cutaway", "the screen recording",
    "the bottom text", "a 3am challenge YouTuber",
    "a rose toy ambassador", "the group chat menace",
    "the unregistered hypercam 2", "low taper fade Ronaldo",
    "the Italian Senate Genshin player", "the phone guy",
    "a delulu stan", "a TikTok NPC streamer",
    "the ocky way", "the brat summer girl", "the demure queen",
    "the very mindful very cutesy one", "the griddy dancer",
    "a hawk tuah specialist", "the aura auditor",
    "the ratio machine", "the W factory", "the L collector",
    "the caught-in-4K victim", "the FYP algorithm",
    "a rent-free tenant", "the vibe checker", "the ick magnet",
    "the beige flag owner", "the situationship survivor",
    "the Subway Surfers gameplay", "a copium addict",
    "the yap king", "the glaze lord", "the PSL rater",
    "the canthal tilt inspector", "the hunter eyes enjoyer",
    "the bonesmash practitioner", "the heightmaxxer",
    "the stairmaxxer", "the jelqer", "the red pill guy",
    "the blackpill nihilist", "the blue pill normie",
    "the based department caller", "an unironic sigma",
    "the group chat historian", "a professional glazer",
    "a deranged fanfic writer", "the timeline menace",
    "the enshittification victim", "a terminally online lurker",
    "the AI slop detector", "a brain-rotted alpha",
    "the lowkey genius", "a highkey fraud",
    "the mewing technique sensei", "the aura bankruptcy lawyer",
    "a chronically offline boomer", "the ratio speedrunner",
    "the discord mod", "the reddit mod",
    "the twitter reply guy", "the linkedin grindset poster",
    "a Letterboxd narcissist", "a Spotify wrapped bragger",
    "the stan account operator", "the burner account owner",
    "a comment section archaeologist", "the notification addict",
    "the do-it-for-the-plot girl", "the roman empire guy",
    "the lore master", "the filler arc character",
    "the post-credits tease", "a seasonal depression arc holder",
    "the cortisol face haver", "a doom scroller",
    "the sleep schedule anarchist", "the melatonin gummy eater",
    "a walking talking red flag", "the weaponized incompetence guy",
    "the quiet kid in the back", "the substitute teacher menace",
    "the school bathroom vaper", "a hallway menace",
    "the cafeteria NPC", "the detention speedrunner",
    "the kid who reminds the teacher about homework",
    "a professional yapper", "the CEO of yapping",
    "the ambassador of glazing", "the minister of cope",
    "the secretary of state of ratio", "the intern at the L factory",
    "the founding father of cringe", "the architect of mid",
    "the prophet of doom scrolling", "a full-time hater",
    "a part-time menace", "the overnight ratio analyst",
    "the emotional support streamer", "a comfort character truther",
    "the kin assigner", "the headcanon enforcer",
    "the AU writer", "the fix-it fic author",
    "the enemies-to-lovers advocate",
    "the found family enthusiast",
    "the unreliable narrator", "the self-insert protagonist",
    "a chronic oversharer", "the vagueposter",
    "the soft block specialist", "the mute-and-move-on practitioner",
    "the block button enthusiast", "the DNI list enforcer",
    "the carrd link bio", "the priv account lurker",
    "the alt account empire builder",

    // === Food / brand memes ===
    "the Grimace Shake survivor", "the Benadryl hat man",
    "the Costco hotdog", "the Chick-fil-A cow",
    "the Travis Scott meal", "the Prime Hydration bottle",
    "the Lunchly enjoyer", "the Stanley cup girlie",
    "the Celsius can", "the Chipotle bowl ratio",
    "a Dollar Tree sigma", "a Walmart cryptid",
    "the Target self-checkout NPC", "a gas station sushi connoisseur",
    "the expired energy drink", "the 3am Taco Bell cashier",

    // === Sports / athlete memes ===
    "LeBron James (the GOAT debate)", "Cristiano Ronaldo (SIUUU)",
    "Messi but humble", "Neymar rolling arc",
    "the Kylian Mbappe turtle meme", "Haaland robot mode",
    "Steph Curry shimmy", "Luka Doncic complaining to the ref",
    "the NFL kicker who missed", "the waterboy",
    "the mascot who got too aggressive",
    "the benchwarmer with main character energy",

    // === Historical / absurdist ===
    "Abraham Lincoln but with drip", "Napoleon short king energy",
    "Sun Tzu but brainrotted", "Genghis Khan sigma arc",
    "Cleopatra slay queen", "the founding fathers in the group chat",
    "caveman who discovered fire", "the asteroid that killed the dinosaurs",
    "the mitochondria (powerhouse of the cell)",
    "the Spanish Inquisition (nobody expected)",
    "Rasputin (unkillable sigma)", "Diogenes the original menace",
    "Julius Caesar (betrayal arc)", "Achilles heel-havin hero",

    // === AI / tech memes ===
    "the AI chatbot", "the sentient algorithm",
    "the deepfake generator", "ChatGPT hallucination",
    "the AI art prompter", "the blockchain bro",
    "the crypto rugpull survivor", "the NFT screenshot enjoyer",
    "the metaverse avatar nobody uses",
    "the smart fridge", "Alexa eavesdropping",
    "the Roomba that gained consciousness",
    "the printer that always jams", "the CAPTCHA test",

    // === Animals / nature memes ===
    "the Shiba Inu (much wow)", "the Cheems",
    "the Doge", "the sad Hamster", "the orange cat",
    "the cat who knocks things off tables",
    "the emotional support alligator",
    "the raccoon with a donut", "the seal that chose violence",
    "the capybara (OK I pull up)", "the quokka selfie",
    "the pigeon with a bread loaf", "the pelican who tried to eat a phone",
    "the mantis shrimp (sees more colors than you)",
    "the orca (killer whale menace)",
    "the opossum (plays dead professionally)",
];
