// Adverbs, prepositional phrases, conjunctions, and relative clauses

export const ADV = [
    // === Truthfulness / emphasis modifiers ===
    "fr fr", "no cap", "on god", "lowkey", "highkey", "deadass",
    "unironically", "literally", "straight up", "ngl",
    "on a stack", "ong", "respectfully", "aggressively",
    "with full aura", "with zero cap",
    "on my mama", "on everything", "on my life",
    "on gang", "on the dead homies", "on Fanum's grave",
    "swear to god", "I put that on", "periodt",

    // === Intensity modifiers ===
    "mad", "hella", "dummy", "crazy", "stupid",
    "insanely", "absurdly", "disgustingly", "violently",
    "astronomically", "exponentially", "catastrophically",
    "unfathomably", "incomprehensibly",
    "unreasonably", "disrespectfully", "offensively",
    "criminally", "illegally", "unconstitutionally",
    "interdimensionally", "cosmically", "apocalyptically",
    "biblically", "mythologically", "historically",
    "unprecedentedly", "unreplicably",
    "atomically", "molecularly", "cellularly",
    "microscopically", "telescopically",
    "seismically", "volcanically", "tectonically",
    "thermonuclearly", "antimatter-level",

    // === Manner / style modifiers ===
    "with the sauce", "with the drip", "with the rizz",
    "on a different level", "like a sigma", "like a boss",
    "in 4K", "in HD", "in broad daylight",
    "silently", "menacingly", "diabolically",
    "NPC-style", "main-character-energy style",
    "with zero remorse", "with maximum disrespect",
    "with the gyatt out", "on demon time",
    "while hitting the griddy", "while mewing",
    "with Italian brainrot energy",
    "at terminal velocity", "with surgical precision",
    "with malicious intent", "with chaotic energy",
    "in slow motion", "in real time", "live on stream",
    "on the main account", "on the burner",
    "in front of god and everybody",
    "in the most unserious way possible",
    "with the confidence of a mediocre man",
    "while making direct eye contact",
    "without breaking character", "while maintaining sigma face",
    "with the aura of a thousand suns",
    "at 2x speed", "at 0.5x speed", "frame by frame",
    "pixel by pixel", "atom by atom",
    "with reckless abandon", "with calculated chaos",
    "with weaponized incompetence",
    "with the energy of a toddler on a sugar high",
    "like it was a speed run", "like it was a tutorial",
    "like it was patch notes", "like it was a cutscene",

    // === Qualifier modifiers ===
    "lowkey but highkey", "not even gonna lie",
    "actually", "genuinely", "legitimately",
    "no joke", "real talk", "facts",
    "100%", "a thousand percent", "no kizzy",
    "objectively", "subjectively but I'm right",
    "allegedly", "reportedly", "according to sources",
    "verified by multiple witnesses",
    "citation needed but we all know",
    "and I have receipts", "and the group chat agrees",
    "and that's not even the worst part",
    "and it gets worse", "and there's footage",
    "and it's on the record", "and the internet saw it",
    "and there's a paper trail",
];

export const PP = [
    // === Cursed / meme locations ===
    "in Ohio", "in the backrooms", "at 3am", "at 3am in Ohio",
    "in the shadow realm", "in the void", "in the Skibidi Toilet dimension",
    "in the phantom zone", "in the upside down",
    "in the trenches", "in the gulag", "in the mud",
    "in the bin", "at rock bottom", "in the darkest timeline",
    "on the edge of the map", "in an unloaded chunk",
    "in the sewer system under Ohio", "in a Walmart parking lot at 3am",
    "in a cursed Roblox server", "at the bottom of the ocean",
    "in a Florida Waffle House", "inside the Among Us vent",
    "inside the Skibidi Toilet", "in a liminal space",
    "in the poolrooms", "at the Italian brainrot convention",
    "in the upside-down Ohio", "in the quantum realm but brainrotted",
    "in the nether", "in the end dimension",
    "at the edge of the observable brainrot",
    "in the multiverse of mid", "at the nexus of cringe",
    "in the uncanny valley", "in an SCP containment breach",
    "in a Mandela Catalogue VHS tape",
    "in an analog horror video", "at the threshold of the void",
    "in the upside down but Ohio edition",
    "in the negative zone", "in the phantom dimension",
    "in a Level 0 backrooms hallway",
    "inside a Shrek 2 DVD special features menu",
    "in the Windows XP bliss field",
    "in a Chuck E. Cheese at midnight",

    // === Grind / hustle locations ===
    "on the sigma grindset", "at the rizz academy",
    "in the mog zone", "at the mewing dojo",
    "in the looksmax clinic", "at the Sigma Summit",
    "at the low taper fade barbershop", "at the gym",
    "in the PSL rating chamber", "at the bonesmash factory",
    "at the aura check station", "in the W factory",
    "at the sigma grindset headquarters",
    "in the heightmaxxing laboratory",
    "at the school of hard mogs", "in the rizz dojo",
    "at the aura rehabilitation center",
    "in the cope therapy waiting room",
    "at the L recovery clinic",
    "in the ratio trauma ward",
    "at the sigma boarding school",
    "at the mewing retreat", "in the bonesmash dojo",
    "at the jaw restructuring facility",
    "in the canthal tilt correction center",
    "at the aura training grounds",

    // === Online / digital locations ===
    "on the FYP", "in the group chat", "in the Discord server",
    "on the timeline", "in the parasocial trenches",
    "in the TikTok trenches", "in the TikTok live chat",
    "on a Subway Surfers screen",
    "in the Family Guy funny moments compilation",
    "during an aura farming session", "on main",
    "on the burner account", "in the Reddit comment section",
    "in the Twitter replies", "on the finsta",
    "in the YouTube comments", "on the Twitch chat",
    "in the Minecraft server", "in the Roblox lobby",
    "on the Among Us server", "in the Fortnite lobby",
    "in the Skibidi Toilet fandom wiki",
    "in a Twitter Space at 2am", "on someone's Instagram close friends",
    "in the LinkedIn DMs", "on the company Slack",
    "in a Zoom breakout room", "in the BeReal notification",
    "on a Threads post nobody saw", "in the Tumblr discourse",
    "on a dead subreddit", "in the 4chan archives",
    "in a Google Doc with 47 editors",
    "in the notes app", "in the drafts folder",
    "in the spam folder", "in the recycle bin",
    "in a private Spotify playlist", "in the liked songs graveyard",
    "in the shared Google Drive",
    "in the Notion database nobody updates",
    "on a Figma board", "in the Jira backlog",
    "in the pull request comments",
    "in a Stack Overflow answer from 2014",
    "in the npm dependency tree",

    // === Activity / temporal locations ===
    "at the function", "during a mewing session",
    "while hitting the Griddy", "on their skibidi arc",
    "in their villain era", "in their flop era",
    "in the Costco food court", "on demon time",
    "during a devious lick attempt",
    "while doing the griddy on the haters",
    "in the middle of a rizz attempt",
    "during an Italian brainrot episode",
    "while going full Bombardiro Crocodilo",
    "in the middle of a Tralalero Tralala sighting",
    "at the brainrot Olympics", "at the cope factory",
    "during a ratio speedrun", "in the coping chamber",
    "while on a W streak", "during an L spree",
    "at the hawk tuah establishment",
    "during a job interview", "at Thanksgiving dinner",
    "in the school hallway", "at the dentist",
    "during a funeral (not theirs)", "at the DMV",
    "during a first date", "at church",
    "in the Uber", "in the fitting room",
    "during a fire drill", "at the orthodontist",
    "at the family reunion", "during silent reading time",
    "in the school cafeteria", "during the SATs",
    "at a wedding reception", "during a job interview on Zoom",
    "in the middle of a presentation",
    "during a parent-teacher conference",
    "at the pediatrician's office", "during a therapy session",
    "while on hold with customer service",
    "in the drive-thru at 2am",
    "during a power outage", "while the teacher was talking",
];

export const CONJ = [
    // === Standard ===
    "and", "but", "because", "so", "and then",

    // === Brainrot conjunctions ===
    "but fr", "because lowkey", "and honestly",
    "but like", "so basically", "and ngl",
    "but on god", "and deadass", "because ong",
    "so like", "and then fr fr", "but no cap",
    "because actually", "and respectfully",
    "but unironically", "and I'm not even capping",
    "so anyway", "and then out of nowhere",
    "but wait it gets worse", "and you won't believe this but",
    "because why not", "and that's when",
    "but the thing is", "so check this out",
    "and the plot thickens because",
    "but in a plot twist", "and then the aura shifted because",

    // === Expanded conjunctions ===
    "but here's where it gets crazy:", "and then mid-sentence",
    "because the prophecy demanded it", "so naturally",
    "and despite all logic", "but against all odds",
    "because the vibes dictated", "so in classic fashion",
    "and without warning", "but in their defense",
    "because the timeline required it",
    "and in a turn nobody predicted",
    "but the lore goes deeper because",
    "so anyway that's why", "and chat you're not ready for this but",
    "because the algorithm willed it",
    "but the NPC dialogue kicked in and",
    "and as foretold by the group chat,",
    "but mid-mew,", "and during the aura audit,",
    "because somewhere in Ohio,", "so in the post-credits,",
    "but the foreshadowing was right there because",
    "and in the director's cut,",
    "but what they didn't show you was",
    "because the simulation demanded it",
    "and per the sigma handbook,",
];

export const REL = [
    // === Standard ===
    "who", "that", "which",

    // === Brainrot modifiers ===
    "who literally", "who lowkey", "that deadass",
    "which honestly", "who fr fr", "that unironically",
    "who on god", "that no cap", "which ngl",
    "who allegedly", "that apparently",
    "who I kid you not", "that suspiciously",
    "which for some reason", "who despite everything",
    "that against all odds", "which to everyone's shock",
    "who in a turn nobody saw coming",
    "that in classic Ohio fashion",
    "which in true brainrot form",
    "who with zero aura", "that with full sigma energy",
    "which to be fair", "who respectfully",
    "that menacingly", "who diabolically",

    // === Expanded relative clauses ===
    "who sources say", "that the group chat confirmed",
    "which the algorithm blessed", "who chat can verify",
    "that multiple witnesses reported",
    "which according to the lore", "who canonically",
    "that in the post-credits scene", "which in the DLC",
    "who during the live stream", "that in the unedited footage",
    "which the mods deleted but we all saw",
    "who your FBI agent confirmed",
    "that the timeline will never forget",
    "which per the sigma handbook",
    "who the prophecy foretold", "that the council approved",
    "which despite the community notes",
    "who in the extended universe",
    "that per the ratio court ruling",
    "which the aura police documented",
    "who in a fit of brainrot",
    "that while mewing",
    "which for legal reasons is a joke",
    "who off the record",
    "that the algorithm keeps recommending",
    "who against medical advice",
    "that in violation of several treaties",
    "which technically speaking",
    "who in an unprecedented move",
    "that without consulting anyone",
    "which in a display of hubris",
    "who to the horror of witnesses",
    "that in a moment of clarity",
    "which after years of foreshadowing",
];
