// Transitive and intransitive verb phrases

export const TV = [
    // === Core brainrot verbs ===
    "rizzes up", "mogs", "mews at", "hits the Griddy on",
    "Fanum taxes", "aura checks", "sigma stares at",
    "gyatt checks", "out-pizzas", "ratio'd",
    "does the Hawk Tuah on", "NPC walks toward",
    "devious licks", "no diffs", "hard carries",
    "soft launches with", "is glazing", "edge lords",
    "puts the Fanum tax on", "mog walks past",
    "brain rots with", "unc walks toward", "tweaks over",
    "ick lists", "cooks", "yaps at", "locks in with",
    "caseoh's", "is mogging on", "gives aura to",
    "steals the gyatt of", "collabs with", "farms aura from",
    "does an aura check on", "skibidis all over",
    "main characters past",

    // === Dominance / competition verbs ===
    "bodies", "clears", "stomps", "washes", "dusts",
    "dogs on", "violates", "packs up", "sends to the shadow realm",
    "catches a body on", "drags", "flames", "roasts",
    "exposes", "ratio's", "puts on blast",
    "catches in 4K", "screenshots and reports",
    "sends the Tung Tung Tung on",
    "folds", "absolutely cooks", "ends the career of",
    "laps", "outpaces", "walks all over",
    "one-taps", "speed runs past", "any-percents",
    "diff checks", "skill gaps", "level gaps",
    "stat checks", "gear checks", "damage checks",
    "tower dives", "spawn camps", "teabags",
    "360 no-scopes", "wall-bangs", "trick-shots",
    "clutches against", "aces past",

    // === Social / influence verbs ===
    "gatekeeps", "gaslights", "girlbosses past",
    "ghosted", "benched", "breadcrumbed", "zombied",
    "lovebombs", "orbits", "simps for", "thirsts over",
    "stans", "glazes", "yaps about", "yapocalypses at",
    "drags into the discourse",
    "puts on the griddy for", "does a devious lick on",
    "DMed unsolicited opinions to", "subtweeted",
    "quote-tweet dunked on", "parasocially adopted",
    "review-bombed", "ratio'd into oblivion",
    "did a hit tweet about", "left on read",
    "left on delivered", "double texted", "triple texted",
    "sent a voice note to", "reacted with a thumbs down to",
    "unfollowed", "soft blocked", "hard blocked",
    "muted the group chat because of",
    "vaguetweeted about", "posted a thirst trap for",
    "slid into the DMs of", "air-dropped a meme to",
    "community noted", "fact-checked",
    "wrote a callout post about", "made a thread exposing",
    "added to the DNI list", "screen recorded",
    "put in the cringe compilation", "nominated for ratio of the year",

    // === Looksmaxxing verbs ===
    "height mogs", "jaw mogs", "frame mogs",
    "AMOG's", "looksmaxxes past", "mews in front of",
    "bone smashes toward", "PSL rates",
    "canthal tilt checks", "wrist mogs",
    "skull mogs", "hairline mogs", "neck mogs",
    "bone structure checks", "norwood checks",
    "eye area mogs", "midface ratio checks",
    "shoulder-to-waist ratio checks", "phenotype mogs",

    // === Content creator verbs ===
    "reacts to", "duets with", "stitches with",
    "ratio farms", "engagement baits", "rage baits",
    "content farms", "collabs with", "clickbaits",
    "parasocially bonds with", "donowalls",
    "stream snipes", "clout chases", "clout sharks",
    "DMCA's", "copyright strikes",
    "brand deals past", "sponsors over",
    "unboxes in front of", "tier lists",
    "makes a 3-hour video essay about",
    "makes an apology video for", "clickbaits with",
    "thumbnail faces at", "does a mukbang with",
    "does a 24-hour challenge with",
    "does a whisper ASMR about",

    // === W/L culture verbs ===
    "gives the W to", "hands the L to", "cope checks",
    "seethe checks", "touch-grasses", "skill issues",
    "vibe checks", "fit checks", "reality checks",
    "Bombardiro Crocodilos on", "Tralalero Tralalas past",
    "humble checks", "ego checks", "age checks",
    "receipts checks", "fact checks with screenshots",
    "posts the L of", "screenshots the ratio of",
    "serves a cease and desist to", "files a noise complaint about",
    "sends a formal ratio to", "issues a vibe violation to",
    "suspends the aura license of", "revokes the sigma card of",
];

export const IV = [
    // === Core brainrot states ===
    "is hitting the Griddy", "is bussin", "is gooning",
    "is locked in", "is on demon time", "is in their bag",
    "is yapping", "is tweaking", "is cooked",
    "is down bad", "is up good", "is mewing",
    "stays winning", "just exists", "is edging",
    "is on their villain arc", "is looksmaxxing",
    "is bonesmashing", "has main character energy",
    "is literally an NPC", "goes goblin mode",
    "is the moment", "has no chill",
    "is giving", "is serving", "is absolutely unhinged",
    "understood the assignment", "ate and left no crumbs",
    "did not pass the vibe check", "is chronically online",
    "is farming aura", "has negative aura",
    "is in their flop era", "is in their redemption arc",
    "just dropped their new era", "is lowkey tweaking",

    // === Performance / excellence states ===
    "is slaying", "is eating", "is cooking",
    "is absolutely feasting", "is on a heater",
    "is in their prime", "is popping off", "is going crazy",
    "is going dummy", "is going sicko mode",
    "is having a moment", "is having a glow up",
    "is in their bag rn", "is cracked", "is built different",
    "is on their grind", "is on god rn",
    "is the blueprint", "is a whole mood",
    "is doing numbers", "is going nuclear",
    "is speedrunning success", "is any-percenting life",
    "is in their god arc", "is ascended",
    "is operating on a different frequency",
    "is in their final form", "is going super saiyan",
    "is running it back", "is on their protagonist arc",
    "is sigma grinding in silence",
    "is carrying the team", "is solo queuing through life",
    "is in creative mode", "is playing on easy difficulty",
    "is on new game plus", "is max prestige",
    "is in the hyperbolic time chamber",

    // === Negative / failure states ===
    "is crashing out", "is down horrendous",
    "is fumbling the bag", "is taking an L",
    "is catching strays", "is getting packed up",
    "is getting ratioed", "is getting clowned",
    "is getting violated", "has fallen off",
    "is on thin ice", "is in the mud", "is finished",
    "is washed", "is a walking L", "is cooked beyond repair",
    "is getting exposed", "is getting dragged",
    "is getting sent to the shadow realm",
    "is getting memed on", "is becoming a copypasta",
    "is a cautionary tale", "is the villain of the arc",
    "is getting community noted", "is getting debunked",
    "is getting fact-checked by the timeline",
    "is on their downfall arc", "is getting milkshake ducked",
    "is imploding on main", "is fumbling publicly",
    "is self-reporting", "is getting the ick from themselves",
    "is playing on hard mode with no save points",
    "is speedrunning their own downfall",
    "is any-percenting the L", "is glitching through the floor",
    "is stuck in a loading screen", "is buffering",

    // === Emotional / mental states ===
    "is coping", "is seething", "is malding",
    "is living rent free", "is crying in the club",
    "is fighting demons", "is not okay",
    "is going through it", "is having a villain origin story",
    "is dissociating", "is touch-starved",
    "is terminally online", "is doom scrolling",
    "is in a parasocial relationship", "is gaslighting themselves",
    "is running on zero sleep and spite",
    "is having an existential crisis at Wendy's",
    "is projecting", "is deflecting", "is spiraling",
    "is chronically unserious", "is menacingly silly",
    "is delulu and thriving", "is fighting their inner NPC",
    "is in their joker arc", "is rotting in bed",
    "is bed-rotting professionally", "is derealized",
    "is having their 13th reason",
    "is staring at the ceiling at 3am",
    "is overthinking that text from 2019",
    "is writing a trauma dump in the notes app",
    "is about to post something unhinged",
    "is one bad day away from a villain arc",
    "is holding it together with caffeine and delusion",
    "is functioning on pure spite and audacity",

    // === Aura / social capital states ===
    "is gaining aura", "is losing aura",
    "is aura farming", "has infinite aura",
    "has negative infinity aura", "is aura bankrupt",
    "just had an aura explosion", "is on an aura streak",
    "has aura insurance", "is aura laundering",
    "is experiencing aura hyperinflation",
    "just aura defaulted", "is in aura debt",
    "has an aura credit score of 3",
    "is aura embezzling", "is running an aura ponzi scheme",
    "just got aura audited", "is aura insolvent",

    // === Trend / era states ===
    "is in their brat era", "is being very demure",
    "is being very mindful very cutesy",
    "is in their delulu era", "is in their soft launch era",
    "is in their situationship era",
    "is in their Roman Empire phase",
    "is in their no-thoughts-just-vibes era",
    "is on a sigma grindset", "is on their W arc",
    "just went six-seven", "is doing the rizzler walk",
    "is Tralalero Tralala-ing", "is going full Bombardiro",
    "is in their mob wife era", "is in their clean girl era",
    "is in their cottagecore to dark academia pipeline",
    "is in their coquette era", "is in their tomato girl summer",
    "is in their rat girl era", "is in their feral era",
    "is in their revenge arc", "is in their glow-down era",
    "is in their reputation era", "is in their apology video era",
    "is going through their Kanye arc",
    "is in their silent protagonist era",
    "is in their anime training arc",
    "is in their post-credits scene",
    "is in their flop to redemption pipeline",
    "is in their gaslight gatekeep girlboss era",
    "is in their quiet luxury era", "is in their loud budgeting era",
    "is in their soft hiking era", "is in their girl dinner era",
    "is in their roman empire of roman empires era",
    "is in their delusional self-confidence era",
    "is in their I-don't-chase-I-attract era",
];
